### ISSUE TITLE
Possibility for numbered sidenotes?

### ISSUE THREAD

**Issue by ekstroem** [nstrayer/tuftesque#15]
I think the theme is wonderful so kudos for making it. Is it possible to make *numbered* sidenotes. For the `tufte` packages they are obtained by using footnotes, `lalala^[adasd]` but I can seem to get that to work with the theme

**Comment by mcguinlu** [comment]
This may no longer be of interest @ekstroem, but I was keen to implement this functionality on my own blog and recently worked out how to do it, so I said I'd reply here for anyone else who is stuck!

Numbered sidenotes are supported by the `tuftesque` theme's CSS, but footnotes are not automatically converted to sidenotes (I think due to the way Hugo renders Rmarkdown, but not sure). Rather, you have to manually wrap the text you want in the `sidenote` class, and preface this with an empty span with class `sidenote-counter`. So for example:

`<span class = "sidenote-counter"></span><span class = "sidenote">BlahBlahBlah</span>`

One thing that tripped me up intially was the need for this span with class `sidenote-counter` - this is what defines the cross-reference number in the main text and which enables the automatic increment with each subsequent sidenote.

Writing all the raw HTML in your blog is a pain (or at least I think so!), so I'd recommend using a small helper function, similar to `tufte::margin_note()`, to insert the correct HTML - here's mine in case it's useful:

https://github.com/mcguinlu/blog/blob/1969bad28c97b57001acbd7bf8edb63ac20589cd/R/sidenote.R#L1-L7

One other thing to note is that you will need to add the `.sidenote` class to [this CSS definition](https://github.com/nstrayer/tuftesque/blob/8ce6ad6ed1ff96ba08f198445d884636316e04ff/static/css/tuftesque.css#L604-L619), so that sidenotes are appropriately wrapped on small screens. The link to my implementation of this is below for reference!

https://github.com/mcguinlu/blog/blob/main/static/css/override.css#L610-L625

**Comment by ekstroem** [comment]
Thanks!  That was a nice solution.

I've done a bunch of tinkering with my blog page since my post in 2018 and have a construction that seems to be working (see https://sandsynligvis.dk/2020/09/15/tips-til-l%C3%A6se-og-afkode-statistikken-i-videnskabelige-artikler/ ) for an example.

To be honest my solution was a lot less elegant than yours and consists of fixing footnotes and sidenotes by replacing some HTML through the `build.R` file. Maybe it would be worth revisiting my old code and reimplement your solution. Seems a lot more maintainable.
